apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: "{{  .Chart.Name }}-virtualservice"
spec:
  gateways:
    - "{{  .Chart.Name }}-gateway"
  hosts:
    - "{{ .Values.istio.gateway.host }}"
  http:
    - route:
        - destination:
            host: "{{  .Chart.Name }}"
            port:
              number: {{ .Values.service.servicePort }}
