apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ .Chart.Name }}-digital-wallet
  labels:
    app: digital-wallet
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ .Chart.Name }}-digital-wallet
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: {{.Values.chartCatalogUrl}}/{{.Values.digital-wallet.chartName}}-{{.Values.digital-wallet.version}}.tgz
      namespace: {{ .Values.appNamespace }}
