apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ .Chart.Name }}-support
  labels:
    app: banking-support
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ .Chart.Name }}-support
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: {{.Values.chartCatalogUrl}}/{{.Values.frontend.chartName}}-{{.Values.frontend.version}}.tgz
      namespace: {{ .Values.appNamespace }}
